#!/bin/bash

# execute this script after adding or removing an installer

function joinArr {
  local IFS="$1";
  shift;
  echo "$*";
}

installers_dir="./installers/src/"
list_file="./installers/list"

files=( $(ls $installers_dir) )
list=$(joinArr , ${files[@]})

contents=$(printf "# do not manually edit this file
# this file is automatically regenerated by scripts/rebuild_installers_list.sh on git push
$list")

if [ -f "$list_file" ] ; then
  if [[ $(< $list_file) == "$contents" ]]; then
    echo "Did not need to rebuild installers list"
  else
    rm "$list_file"
    echo "$contents" > $list_file
    echo "Saved rebuilt installers list to $list_file"
  fi
fi
